- README.md
- cmd/computing-provider/ubi.go
- config.toml.sample
- fil-c2.env
- internal/computing/cp_service.go
- internal/computing/k8s_service.go
- util/utils.go
- fix ubi proof report port
- update the task loading method from `configmap` to mount
- update Collateral contract address
> fix ubi bugs

- build/version.go
- config.toml.sample
- internal/computing/cp_service.go
- internal/computing/deploy.go
- wallet/sigs.go
- fix verify ubi signatures
- update space hardware, CPU:5GiB, GPU:20GiB
> fix ubi signature and update space resource

- README.md
improve the zk-task input file download process
> Releases v0.4.2

- build/version.go
- cmd/computing-provider/run.go
- cmd/computing-provider/ubi.go
- config.toml.sample
- constants/utils.go
- internal/computing/cp_service.go
- internal/computing/docker_service.go
- internal/computing/k8s_service.go
- internal/computing/resources_sumary.go
- internal/computing/task_service.go
- internal/models/resources.go
- upgrade the `resource-exporter`
- support UBI task for intel and amd CPU type
- fix submit proof use `ownerAddress`
- add `--show-failed` flag to show the failed ubi task
> fix ubi task can be done in AMD and Intel CPU

- README.md
- config.toml.sample
- internal/computing/cp_service.go
- internal/computing/deploy.go
- internal/computing/k8s_service.go
- update `SWAN_COLLATERAL_CONTRACT="0xdc200f89258e72aC3602dD23BD3642C4bd4eE34e"`
- fix A100 gpu can not be matched
> Fix gpu issue and update collateral contract address

- .gitignore
- Makefile
- build/0x78A170BE72F00F8a49538bc9895377984a8579f3/spaces/HeheSpace/deploy.yml
- build/version.go
- cmd/computing-provider/ubi.go
- constants/utils.go
- internal/computing/cp_aleo_service.go
- internal/computing/cp_fil_service.go
- internal/computing/cp_service.go
- internal/models/cp.go
Add [ubi-aleo](https://github.com/swanchain/devgrants/issues/9) feature
> Add ALEO-ZK-UBI feature

- internal/computing/cp_service.go
- internal/computing/ubi.go
GPU type UBI tasks cannot be executed correctly due to incorrect gpu resource restrictions.
> Fix docker of gpu tasks

- internal/computing/cp_service.go
The API for getting the region cannot be accessible because the request has verification. We are currently offering another API available: `https://ipinfo.io/`
> fix get region limit bug

- cmd/computing-provider/run.go
- internal/computing/cp_service.go
- internal/computing/k8s_service.go
- internal/computing/ubi.go
* Fixed the error that the changeOwnerAddress command reported `ownerAddress is not empty`.
* Fixed the error when using `--repo`
> fix some bug

- build/version.go
- cmd/computing-provider/run.go
- internal/computing/cp_service.go
- internal/computing/cron_task.go
- internal/computing/docker_service.go
- internal/computing/provider.go
- internal/computing/ubi.go
- internal/models/resources.go
- ubi/README.md
- fix new fcp can not receive tasks(add `Autobid=1` default)
* fix  `\\x01` error caused by `resource-exporter` 
* fix `changeOwnerAddress` error
* add  log of ecp running task
> fix ecp and fcp bugs

- cmd/computing-provider/run.go
- conf/config.go
* add valiate repo
* add print log
> Fea check repo

- README.md
- build/version.go
- cmd/computing-provider/main.go
- cmd/computing-provider/utils.go
- conf/config.go
- internal/computing/cp_service.go
- internal/computing/cron_task.go
- internal/computing/ubi.go
- internal/db/db.go
* fix the bug that when run the init command, initialization failed due to check the repo directory
> Fix check repo

- README.md
- build/version.go
- config.toml.sample
- internal/computing/cron_task.go
- internal/computing/docker_service.go
- internal/computing/ubi.go
- internal/db/db.go
- ubi/README.md
- util/response.go
* fixe the bug that fcp failed to do zk-task
* added retries for downloading mcs url and update ubi-task image version to v3.0
> Fix the bug that FCP fails to do zk-task

- internal/computing/cron_task.go
- internal/computing/docker_service.go
- internal/computing/ubi.go
* fix cron expression for update status
* update the time to clean up resources
* add log
> fix cron expression for update status and add log

- internal/computing/buildspace.go
- internal/computing/cron_task.go
Fixed the bug caused by timeout of container status cleanup deployment
> Fixed the bug of cron task deleting job

- build/version.go
- cmd/computing-provider/run.go
- cmd/computing-provider/tablewriter.go
- conf/config.go
- internal/computing/buildspace.go
- internal/computing/cp_service.go
- internal/computing/cron_task.go
- internal/computing/deploy.go
- internal/computing/entity_service.go
- internal/computing/k8s_service.go
- internal/computing/scanner_service.go
- internal/computing/ubi.go
- internal/models/cp.go
- ubi/README.md
- util/response.go
- util/rsa_util.go
* In order to protect the data security of space, add RSA and AES algorithm encryption and decryption
> Add a new dcc feature

- cmd/computing-provider/task.go
- internal/computing/cp_service.go
- internal/computing/cron_task.go
- internal/computing/entity_service.go
- internal/computing/scanner_service.go
- internal/computing/scanner_worker.go
- internal/db/db.go
- internal/models/entitys.go
* Concurrent writes to sqlite cause database to be locked
* Compatible with using `space_uuid` to deploy jobs
> Fix database locked and update the cron tasks of deleting jobs

- README.md
- build/parameters.json
- cmd/computing-provider/task.go
- internal/computing/cp_service.go
- internal/computing/cron_task.go
- internal/computing/deploy.go
- internal/computing/k8s_service.go
- internal/contract/account/account_stub.go
Due to the logic of checking the previous job's status.
> fix cron-task delete job bug

- cmd/computing-provider/run.go
- internal/computing/cron_task.go
- internal/contract/ecp/collateral_stub.go
- internal/contract/ecp/sequencer_stub.go
* add verification contract address
*  update print log
> Add check contract address

- README.md
- cmd/computing-provider/run.go
- cmd/computing-provider/ubi.go
- internal/computing/entity_service.go
- internal/computing/resource_price.go
- internal/computing/space_service.go
- internal/computing/ubi_service.go
- internal/models/entitys.go
- internal/models/resources.go
- ubi/README.md
* Merge 1: Fil-C2-512M and 4: Fil-C2-32G  into 1: Fil-C2
* Adjust the default price of CP resources
* Fixed updating ubi task status bug
> Update task type

- ubi/README.md
add sequencer's **Dynamic Pricing Strategy**: https://docs.swanchain.io/bulders/market-provider/web3-zk-computing-market/sequencer
> add sequencer's Dynamic Pricing Strategy

- build/parameters.json
- conf/config.go
- internal/computing/ecp_image_service.go
- internal/computing/entity_service.go
- internal/computing/resource_price.go
* Supports two formats: `Pricing="true"` and `Pricing=true`
* Print deploy container log
> Hotfix pricing deploy log

- ubi/README.md
the L3's sequencer gas mechanism is [here](https://docs.swanchain.io/bulders/market-provider/web3-zk-computing-market/sequencer)
> Update ecp readme

- internal/computing/ecp_image_service.go
- internal/computing/space_service.go
- internal/computing/ubi_service.go
* Add validate container name
* Add log
> Fix deploy image bug

- build/version.go
- conf/config.go
- internal/computing/cron_task.go
- internal/computing/scan_task_payment.go
- internal/computing/scanner_service.go
- internal/computing/space_service.go
- internal/contract/ecp/task_stub.go
- internal/models/entitys.go
* Change scanning a single task to scanning height
> Fix too many rpc request

- cmd/computing-provider/task.go
- cmd/computing-provider/wallet.go
- internal/computing/cron_task.go
- internal/computing/deploy.go
- internal/computing/entity_service.go
- internal/computing/ubi_service.go
- internal/computing/wire.go
- internal/computing/wire_gen.go
- internal/db/db.go
- internal/models/entitys.go
Use  cron task to check the balance of cp's worker and sequencer to improve  API response requests
> Fix receiving ubi task timeout

- internal/computing/cron_task.go
- internal/computing/resource_price.go
Add a check for whether the K8s client is nil when generating the price file.
> Fix nil pointer check for the K8s client

- cmd/computing-provider/run.go
- internal/computing/ubi_service.go
> fix check cp balance

- README.md
- build/parameters.json
- build/version.go
- ubi/README.md
* Update README.md
* Update `resource-exporter` version to v11.3.1
* Update version to v1.0.1
> Update version to v1.0.1

- internal/computing/docker_service.go
- internal/computing/ecp_image_service.go
- internal/computing/space_service.go
- internal/computing/ubi_service.go
* Print logs when receiving tasks to check for insufficient resources
> add check resource log

- README.md
- build/version.go
- cmd/computing-provider/ubi.go
- go.mod
- go.sum
- internal/computing/cron_task.go
- util/utils.go
* Add mapping `/etc/machine-id` to `resource-exporter`
* Update check `resource-exporter` function
> Update README.md and check version

- internal/computing/ecp_image_service.go
> Fixed mining task timeout bug

- internal/computing/k8s_service.go
- internal/computing/resources_sumary.go
- internal/computing/space_service.go
- internal/models/resources.go
- test/sequencer_service_test.go
* Update the logic of resource filtering node
* Add log for checking resource
> fix FCP fail to create the sampling task when K8s have multi-node

- internal/computing/cron_task.go
- internal/computing/ecp_image_service.go
- internal/computing/entity_service.go
- internal/computing/ubi_service.go
* Cron tasks do not need to scan `rejected` tasks to update status
> Fix the issue of updating the rejected status of a task

- cmd/computing-provider/run.go
- internal/computing/cron_task.go
- internal/computing/ecp_image_service.go
- internal/computing/entity_service.go
- internal/computing/space_service.go
- internal/computing/ubi_service.go
- internal/models/cp.go
* Add `/api/v1/computing/cp/zk_task` api for ubi running on k8s
> Add zk_task  API

- build/version.go
- internal/computing/space_service.go
- internal/computing/ubi_service.go
- ubi/README.md
> Update version to v1.1.2
